name: todart_core
publish_to: none
version: 0.0.1
environment:
  sdk: '>= 2.8.0'
dependencies:
  dotenv: ^2.0.0
  uuid: ^2.2.2
  firedart: ^0.8.2
  test: ^1.15.7
  dart_jsonwebtoken: ^1.5.1
  ioco:
    path: '../../ioco'
  hashio:
    path: '../../hashio'